DROP TABLE IF EXISTS schedules;
CREATE TABLE IF NOT EXISTS schedules (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL,
  day INTEGER NOT NULL,
  start_at TIME NOT NULL,
  end_at TIME NOT NULL
);
DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  firstname VARCHAR(255) NOT NULL,
  lastname VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS userschedules;
CREATE TABLE IF NOT EXISTS userschedules (
  id SERIAL PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  day INTEGER NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL
);